<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">

<html>
<head>
	<title><xsl:value-of select="/rss/channel/title"/> - RSS</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<xsl:choose>
	<xsl:when test="/rss/channel/image">
		<link rel="icon" type="image/jpeg">
			<xsl:attribute name="href"><xsl:value-of select="/rss/channel/image/url"/></xsl:attribute>
		</link>
	</xsl:when>
	<xsl:otherwise>
		<link rel="icon" type="image/png" href="https://radio.djazz.se/podcasts/favicon.png" />
	</xsl:otherwise>
	</xsl:choose>
	<link rel="stylesheet" type="text/css" href="https://radio.djazz.se/podcasts/podcast.css" />
</head>
<body>
	<p class="explanation">
		This is a podcast RSS feed generated by <xsl:value-of select="/rss/channel/generator"/>. It is meant for consumption by podcast feed readers using the URL in the address bar.
	</p>
	<div id="content">
		<div class="channel-header last">
			<h1>
				<xsl:if test="/rss/channel/image">
					<div id="channel-image">
						<a target="_blank">
							<xsl:attribute name="href"><xsl:value-of select="/rss/channel/itunes:image/@href"/></xsl:attribute>
							<img>
								<xsl:attribute name="src">
									<xsl:value-of select="/rss/channel/image/url"/>
								</xsl:attribute>
								<xsl:attribute name="title">
									<xsl:value-of select="/rss/channel/image/title"/>
								</xsl:attribute>
							</img>
						</a>
					</div>
				</xsl:if>
				<xsl:value-of select="/rss/channel/title"/>
			</h1>
			<div class="channel-subtitle">
				<xsl:value-of select="/rss/channel/itunes:subtitle"/>
			</div>
			<div class="channel-description">
				<xsl:value-of select="/rss/channel/description"/>
			</div>
			<div class="channel-author">
				<xsl:value-of select="/rss/channel/itunes:author"/>
				<a style="font-size: large;font-weight: 600;">
					<xsl:attribute name="href">
						<xsl:value-of select="/rss/channel/link"/>
					</xsl:attribute>
					<xsl:attribute name="target">_blank</xsl:attribute>
					<i class="fas fa-globe"></i>
				</a>
			</div>
			<div class="channel-feed">
				<a target="_blank">
				<xsl:attribute name="href"><xsl:value-of select="/rss/channel/atom:link/@href"/></xsl:attribute>
				<i class="fas fa-rss-square"></i> RSS Feed
				</a>
			</div>

			<i class="far fa-calendar"></i> <xsl:value-of select="/rss/channel/lastBuildDate"/> |
			<xsl:value-of select="count(/rss/channel/item)"/> episodes


		</div>
		<xsl:for-each select="/rss/channel/item">
			<div class="channel-item">
				<div class="episode-title">
				<h2>
					<a>
						<xsl:attribute name="href">
							<xsl:value-of select="link"/>
						</xsl:attribute>

						<xsl:attribute name="target">_blank</xsl:attribute>
						<xsl:value-of select="title"/>
					</a>
					<a>
						<xsl:attribute name="href">javascript:audioplayer.src='<xsl:value-of select="enclosure/@url"/>?play';audioplayer.play();</xsl:attribute>
						<i class="far fa-play-circle"></i>
					</a>
					<xsl:if test="itunes:image">
					<div class="episode-image">
						<a target="_blank">
							<xsl:attribute name="href"><xsl:value-of select="itunes:image/@href"/></xsl:attribute>
							<img>
								<xsl:attribute name="src">
									<xsl:value-of select="itunes:image/@href"/>
								</xsl:attribute>
								<xsl:attribute name="title">
									<xsl:value-of select="title"/>
								</xsl:attribute>
							</img>
						</a>
					</div>
					</xsl:if>
				</h2>
				<h3>
					<xsl:if test="itunes:author">
						<xsl:value-of select="itunes:author"/>
					</xsl:if>
				</h3>
				</div>

				<div class="episode-description">

				<xsl:if test="description">
					<p>
						<xsl:value-of select="description"/>
					</p>
				</xsl:if>

				</div>
				<p class="episode_meta">
					<i class="far fa-calendar"></i> <xsl:value-of select="pubDate" /> |
					<i class="fas fa-stopwatch"></i> <xsl:value-of select="itunes:duration"/> |
					<a>
						<xsl:attribute name="href">
							<xsl:value-of select="enclosure/@url"/>?ref=new_window
						</xsl:attribute>
						<xsl:attribute name="target">_blank</xsl:attribute>
						<i class="fas fa-download"></i>
						<xsl:value-of select='format-number(number(enclosure/@length div "1024000"),"0.0")'/>MB
					</a>
				</p>
			</div>
		</xsl:for-each>
	</div>
	<div class="channel-copyright">
		<i class="far fa-copyright"></i> <xsl:value-of select="/rss/channel/copyright"/>
		<br/><br/>
		<a href="https://github.com/PhilGoud/podcast-XSL-template" target="_blank">XSL template by PhilGoud</a>, modified by djazz
	</div>

	<div class="player">
		<audio preload="none" controls="controls" id="audioplayer"></audio>
	</div>

	<script>

// convert text into html
document.querySelectorAll('.channel-description, .episode-description').forEach(function (n) {
	n.innerHTML = n.textContent
})

	</script>
</body>
</html>
</xsl:template>
</xsl:stylesheet>

